### Récupérer tous les articles ###
GET http://localhost:3001/articles

### Récupérer les articles à partir de la position 5, en prenant les 10 premiers éléments ###
GET http://localhost:3001/articles?skip=5&take=10

### Récupérer l'article ayant l'id 1 ###
GET http://localhost:3001/articles/1

### Ajouter un nouvel article ###
POST http://localhost:3001/articles
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywiZW1haWwiOiJhbmFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg0NTI1MjU1LCJleHAiOjE2ODQ2OTgwNTV9.jXYvNXc6cTgKR7kGtVHAsBLGNEbNLnJa2BiIFoqmX5U

{
    "title": "Nouvel article",
    "content": "Contenu de l'article",
    "image": "image-UHVDFJVND",
    "categories": [{"id": 1}]
}

### Mettre à jour l'article ayant l'id 1 ###
PATCH http://localhost:3001/articles/107
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywiZW1haWwiOiJhbmFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg0NTI1MjU1LCJleHAiOjE2ODQ2OTgwNTV9.jXYvNXc6cTgKR7kGtVHAsBLGNEbNLnJa2BiIFoqmX5U

{
    "title": "Article mis à jour",
    "content": "Nouveau contenu",
    "image": "new-image-UHVDFJVND",
    "categories": [{"id": 2}]
}

### Supprimer l'article ayant l'id 1 ###
DELETE http://localhost:3001/articles/107
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywiZW1haWwiOiJhbmFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg0NTI1MjU1LCJleHAiOjE2ODQ2OTgwNTV9.jXYvNXc6cTgKR7kGtVHAsBLGNEbNLnJa2BiIFoqmX5U