### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "anas@example.com",
    "password": "password123",
    "name":"anas"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "anas@example.com",
    "password": "password123",
    "name":"anas"
}