### Récupérer tous les commentaires ###
GET http://localhost:3001/commentaires

### Récupérer les commentaires à partir de la position 5, en prenant les 10 premiers éléments ###
GET http://localhost:3001/commentaires?skip=5&take=10

### Récupérer le commentaire ayant l'id 1 ###
GET http://localhost:3001/commentaires/1

### Ajouter un nouvel commentaire ###
POST http://localhost:3001/commentaires
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywiZW1haWwiOiJhbmFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg0NTI1MjU1LCJleHAiOjE2ODQ2OTgwNTV9.jXYvNXc6cTgKR7kGtVHAsBLGNEbNLnJa2BiIFoqmX5U

{
    "email": "anas@enset.com",
    "content": "Contenu de le commentaire",
    "articleId": 107
}

### Mettre à jour le commentaire ayant l'id 1 ###
PATCH http://localhost:3001/commentaires/1015
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywiZW1haWwiOiJhbmFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg0NTI1MjU1LCJleHAiOjE2ODQ2OTgwNTV9.jXYvNXc6cTgKR7kGtVHAsBLGNEbNLnJa2BiIFoqmX5U

{
    "content": "Contenu mise à jour de le commentaire"
}

### Supprimer le commentaire ayant l'id 1 ###
DELETE http://localhost:3001/commentaires/107
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNywiZW1haWwiOiJhbmFzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg0NTI1MjU1LCJleHAiOjE2ODQ2OTgwNTV9.jXYvNXc6cTgKR7kGtVHAsBLGNEbNLnJa2BiIFoqmX5U